### PR TITLE
Add rule for `rand(Bool)` instead of `rand() < 0.5`

### PR DESCRIPTION
**Pull request by iuliadmtru**
After [this Slack thread](https://julialang.slack.com/archives/C680MM7D4/p1725208125951569).

### CODE REVIEW

**Comment by iuliadmtru** [comment]
The fix does not remove the assignment in cases like:
```julia
x = rand()
if x < 0.5
    ...
end
```

This fixes to:
```julia
x = rand()
if rand(Bool)
    ...
end
```

**Comment by imciner2** [comment]
> The fix does not remove the assignment in cases like:
> 
> ```julia
> x = rand()
> if x < 0.5
>     ...
> end
> ```
> 
> This fixes to:
> 
> ```julia
> x = rand()
> if rand(Bool)
>     ...
> end
> ```

This is different code semantically. If `x` was being used anywhere inside the if statement, then this can cause different execution behavior, since now the entrance to the if statement is guarded by a different random draw. The only way this transformation is valid is if `x` is not used anywhere else.

Take this section of code for instance:
```julia
x = rand()
if x < 0.5
    y = sqrt(0.5 - x)
end
```
Under this transformation, it is now possible to end up with a domain error in the square root when it wasn't before - because if this is transformed to 
```julia
x = rand()
if rand(Bool)
    y = sqrt(0.5 - x)
end
```
then there is no longer a guarantee that `x` is less than 0.5 allowing `0.5 - x` to be always positive. It could be that `rand(Bool)` returns true when `x=rand()` has returned 0.75 for instance.

**Comment by iuliadmtru** [comment]
I hadn't thought of that! I would say then either just remove the autofix, or remove altogether the pattern that checks for assigning `rand()` to a variable and using that variable (and might as well keep the autofix in that case). Not sure which is better.

**Comment by iuliadmtru** [comment]
Other ideas:
- keep this as a partial fix, needing checking by whoever runs the runs (not nice)
- write two separate rules, one for `rand() < 0.5` with autofix, one for `x = rand(); x < 0.5` without autofix

**Comment by aviks** [comment]
> write two separate rules, one for rand() < 0.5 with autofix, one for x = rand(); x < 0.5 without autofix

maybe this is the best way forward?

**Comment by iuliadmtru** [comment]
I split it in two rules. The test files are the same, only the rule names differ (and the tests they pass/fail for of course). The name for the second rule is not very inspired...

**Review by aviks — COMMENTED** [review]
Looks good. Can we add a description of some sort in the rule definition files so that I'm not confused when I see this in a few months?

**Pull request merged**
